[workspace]
members = ["solitaire-solver"]

[package]
name = "peg-solitaire"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = {version = "0.16.1", features = ["wayland"]}
bevy_vector_shapes = "0.10.0"
futures-lite = "2.6.0"
solitaire-solver = { path = "./solitaire-solver", version = "0.0.1" }
solution-cache =  { path = "./solution-cache", version = "0.0.1" }

[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"
opt-level = 3
strip = true

# run build.rs in release mode, otherwise it takes 100 years
[profile.dev.build-override]
opt-level = 3
debug = false

[profile.release.build-override]
opt-level = 3
