on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

name: WASM

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          target: wasm32-unknown-unknown
          profile: minimal
          toolchain: stable
      - name: Cache wasm-bindgen-cli
        id: cache-wasm-bindgen
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/wasm-bindgen
          key: wasm-bindgen-${{ hashFiles('Cargo.lock') }}

      - name: Install Bindgen
        if: steps.cache-wasm-bindgen.outputs.cache-hit != 'true'
        run: |
          WASM_BINDGEN_VERSION=$(cargo metadata --format-version 1 | \
            jq -r '.packages[] | select(.name == "wasm-bindgen") | .version')
          cargo install wasm-bindgen-cli --version $WASM_BINDGEN_VERSION
      - name: Install Binaryen
        run: sudo apt install binaryen
      - name: Install Brotli
        run: sudo apt install brotli
      - name: Build WASM dist
        run: make
      - name: Upload artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: www/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
